
services:
  cafe:
    container_name: cafe
    restart: always
    image: node:20.14.0
    ports:
      - 7000:3800
    environment:
      - PORT=3800
    volumes:
      - ./:/usr/src/cafe
    working_dir: /usr/src/cafe

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

  
networks:
  client-network:
    driver: bridge
